### ISSUE TITLE
Term construction via template?

### ISSUE THREAD

**Issue by CrashBurnRepeat** [ztangent/FOL.jl#5]
@ztangent I'm not sure if I'm just missing an easier way to do this (or if there are more `Julog`-ian ways to do it) but I've been trying to construct some sort of "template logic" that I can then populate with more specific terms. As a short description of what I mean, I've prepared some code 😄  (It does use some Julia 1.5 syntactic sugar though... `;funcs` instead of `funcs=funcs`)
```
funcs = Dict()
funcs[:sin] = sin
funcs[:square] = x -> x * x

op_def(func,input,comp,output) = @julog $(comp)($(func)($input),$output)

sin_def = op_def(
    :sin,
    π/2,
    Symbol("=="),
    1
)

square_def = op_def(
    :square,
    5,
    Symbol("<="),
    25
)

@assert resolve(sin_def, Clause[]; funcs)[1]==true
@assert resolve(square_def, Clause[]; funcs)[1]==true
@assert resolve(@julog(and(:sin_def, :square_def)), Clause[]; funcs)[1]==true
```

The idea is more programmatic generation of `Julog` logic and I didn't see examples like this in the documentation. There were examples on how to use custom functions, but without being able to modify a template, it's impossible to create the `and` expression with just the `funcs` argument. Does that make sense, or would it help to elaborate?

As a side note, I've been curious on your vision for `Julog`. Is the idea to keep it as close to the original `Prolog` as is feasible, or is greater integration into `Julia` the goal?

Thanks as always!

**Comment by ztangent** [comment]
I'm a little confused by what the goal is here, in terms of constructing a "template logic" -- is the idea to programmatically generate a list of Julog clauses or terms? 

If the hope is to programmatically construct a list of terms within an `and` expression, you could just do either of:
```julia
make_and(term1, term2) = @julog and(:term1, :term2)
make_and(terms...) = Compound(:and, terms)
```
It's not clear to me why you would need to pass things through `funcs` at all.

As for your question about vision, I intend to keep Julog as close to Prolog semantics as possible. Custom functions and partial support for [semantic unification](https://en.wikipedia.org/wiki/Unification_(computer_science)#E-unification) are really the only differences from Prolog right now. I'm also hoping to improve performance some day by supporting [pre-compilation of Julog predicates](https://www.it.uu.se/research/csd/theses/0026.pdf) and [query-order optimization](https://www.researchgate.net/profile/Benjamin_Wah/publication/3496571_Efficient_Reordering_of_Prolog_Programs/links/55fa751608aeafc8ac3a733c/Efficient-Reordering-of-Prolog-Programs.pdf), but that's about it in terms of the roadmap.

**Comment by CrashBurnRepeat** [comment]
The larger problem I'm trying to address is getting Julog to work in tandem with other, non-Julog code that might want to pass it variables or particular functions to evaluate in the resolution step. This is what my example was trying to get at, that the particular type of equivalence function (`==` or `<=`) or evaluation function (`sin` or `square`), as well as variables, might be passed to Julog by another part of the code, or even interactively from a user. The structure of the logic would be the same, but the particulars could change.

To support this, I wanted to create parameterized Julog terms (what I called templates, maybe there's a better word?) that could be combined into more complex terms, but I was having trouble using the `funcs` argument in `resolve` to do this.

For instance, if `op_def` were instead defined as
```
new_op_def = @julog comp(func(input), output)
```
then there would be a `funcs1` you could construct to make
```
resolve(sin_def, Clause[]; funcs) == resolve(new_op_def, Clause[]; funcs1)
```
and another to make
```
resolve(square_def, Clause[]; funcs) == resolve(new_op_def, Clause[]; funcs1)
```
but there would be no way (so far as I can see) to construct `funcs1` to make
```
resolve(@julog(and(:sin_def, :square_def)), Clause[]; funcs)
```
equivalent to 
```
resolve(@julog(and(:new_op_def, :new_op_def)), Clause[]; funcs1) 
```

So in that sense, my closure-style definition for `op_def` is something of a workaround.

Does that clarify things at all? Please let me know if I skipped a beat.

**Comment by ztangent** [comment]
I think I better see what you're trying to do now, though I'm still struggling to understand the exact use case. You're right that "there would be no way (so far as I can see) to construct `funcs1` to make `resolve(@julog(and(:sin_def, :square_def)), Clause[]; funcs)` equivalent to `resolve(@julog(and(:new_op_def, :new_op_def)), Clause[]; funcs1)`", because `:new_op_def` refers to the same Julog term.

To see this, suppose we replaced `:new_op_def` with a variable `X`, giving the term `and(X, X)`. `and(X, X)` will unify with `and(:new_op_def, :new_op_def)`, but it could never possibly unify with `and(:sin_def, :square_def)`. So it's not a matter of what you pass in through the `funcs` keyword at all -- it's that `and(:new_op_def, :new_op_def)` could never be treated as a template in the way you want it too, because both instances of :new_op_def will always refer to the same term.

If you're hoping to construct template Julog terms, I think the much more straightforward way to do things is to just create a term with variables, e.g. `and(A, B)`, and then `substitute` those variables accordingly. For example:
```julia
template = @julog and(A, B)
sub = @varsub {A => sin(π/2) == 1, B => square(5) <= 25}
term = substitute(template, sub)
@assert resolve(term, Clause[]; funcs)[1] == true
```
`resolve` also supports an `env` keyword that allows you to specify the top-level mapping from variables to terms, so you can also just do:
```julia
sub = @varsub {A => sin(π/2) == 1, B => square(5) <= 25}
@assert resolve(template, Clause[]; funcs, env=sub)[1] == true
```

Hope this helps!

**Comment by ztangent** [comment]
An addendum: If you're hoping to use variables like `A` in template expressions like `A(B, C)`, where `A` can stand in for some predicate / functor, this is unfortunately not yet possible in Julog, because it effectively amounts to moving from first-order-logic to higher-order-logic. It's something I'd like to support eventually though -- Prolog supports it through use of the built-in [`call/N` predicates](https://www.swi-prolog.org/pldoc/man?section=metacall), which allow you to write template expressions like `call(A, B, C)` in order to express something like `A(B, C)`.

**Comment by ztangent** [comment]
@CrashBurnRepeat So I've just added support for the `call/N` predicate I mentioned above, and you can now do stuff like this!
```julia
julia> funcs = Dict(:square => x->x^2, :cube => x->x^3, :less => (x, y) -> x < y);
julia> env = @varsub {R => less, F => square(2), G => cube(3)};
julia> resolve(@julog(call(R, F, G)), Clause[]; env=, funcs=funcs)
```
If you wanted to do a nested `call` like `@julog(call(R, call(F, 2), call(G, 2))`, where `R` happens to unify with a functions in `funcs`, this won't work by default, because `call` is a predicate, not a function, and so `eval_term` won't know how to recursively evaluate the inner `call(F, 2)` and `call(G, 2)` expressions. _But_ this can be worked around by also defining `call` as a custom function itself:
```julia
julia> funcs[:call] = (f, args...) -> f(args...);
julia> env = @varsub {R => less, F => square, G => cube}
julia> resolve(@julog(call(R, call(F, 2), call(G, 2))), Clause[]; env=env, funcs=funcs)
(true, Any[{R => less, F => square, G => cube}])
```
Hope this more or less resolves your initial question / use case!

**Comment by CrashBurnRepeat** [comment]
My apologies for not responding to your earlier responses faster, but this is great! 

An interesting pairing (or at least, one I'm using that feels that way) is with function-like objects. So consider
```
struct PolynomialPredicate
   a
   b
   c
   pred_func
   val
end

function (p::PolynomialPredicate)(x)
   p.pred_func(p.a*x^2 + p.b*x + p.c, p.val)
end
```
The idea is to encapsulate potentially complex data/logic so that the Julog expressions can kept relatively simple. So an example of this in action would be 
```
poly_a = PolynomialPredicate(1, 1, -2, >=, 0)
poly_b = PolynomialPredicate(-1, -3, 5, <, 0)

env = @varsub({A=>poly_a, B=>poly_b})
funcs = Dict(
    :poly_a=>(x)->poly_a(x),
    :poly_b=>(x)->poly_b(x))

@assert resolve(
    @julog(and(call(A,2),call(B,2))),
    Clause[];
    env,
    funcs
    )[1]
```
Ideally, I would show Julog finding the feasible values over a domain, but I'm still learning how to do that 😅 

Anyway, I think what you've shown is enough for me to work with for the near future, perhaps it's best to close for now?

**Comment by ztangent** [comment]
Interesting, I see! I actually think it may be possible to do what you're trying to do without calling out to Julia functions at all, but it might require extensions to Julog that support [constraint logic programming](https://en.wikipedia.org/wiki/Constraint_logic_programming). That's another topic though, so yes, I'll close this for now :)
